### ISSUE TITLE
OSGI DECLARATIVE SERVICES ANNOTATIONS IN AEM

### ISSUE THREAD

**Issue by aman02deep** [Cognifide/AEM-Rules-for-SonarQube#72]
Hi,

AEM-8 Prefer cleaner @SlingServlet annotation.

This rule recommends to use @SlingServlet Annotation but as per OSGI Declarative services (OSGI R6) the new way to create Servlet is: 
@Component(
    immediate = true,
    service = Servlet.class,
    property = {
        "sling.servlet.resourceTypes=project/components/component"
    }
)
@Designate(ocd = SampleOsgiServlet.Configuration.class)

e.g: https://gist.github.com/nateyolles/e1e809485cbb0ef1e04a445ddf53a6d7

I saw couple of more blogs and posts for the same.
Can you please help me with this issue?

**Comment by cduque89** [comment]
Hi we have the same in our code, but according to the latest documentation since AEM 6.2 we should use OSGi annotations. Can you please advice. 

Thanks.

**Comment by chutch** [comment]
Hi, 

yes, since AEM 6.2 and OSGI R6 there is a new recommended way to handle OSGI annotations. 

Thanks for raising the issue, I think that the best possible option would be to introduce new runtime variable that will specify AEM version for the plugin run. The fix will be provided in the future release.

Until then, I would advise you to turn off this particular rule, as it is deprecated for AEM 6.2+
