### ISSUE TITLE
Support disabling rules via //NOSONAR

### ISSUE THREAD

**Issue by kwin** [Cognifide/AEM-Rules-for-SonarQube#78]
AEM rules should be possible to disable with the Java comment `//NOSONAR` (similar to what is possible with the Java Plugin). This currently does not work.

**Comment by chutch** [comment]
Hi @kwin,

thanks for the ticket, it makes much sense. Is this something you'd like to contribute or you're willing to wait as I will need to find volunteer internally?

**Comment by garbacikp** [comment]
Hi @kwin i've just checked this issue since the NOSONAR wildcard is supposed to work with any issue raised, from wherever the issues come from.  [Info](https://groups.google.com/forum/#!topic/sonarqube/kRJpdCc-gHo)

I've done some quick test by self check rules project [code](https://github.com/garbacikp/AEM-Rules-for-SonarQube/blob/issue-78/src/main/java/com/cognifide/aemrules/checks/HttpConstantCheck.java#L44) and this issue was properly igonred.

**Comment by boobootoo2** [comment]
I have tested the NOSONAR comment below on the line of code reporting an HTL issue. The comment below does not suppress the Sonar Error. I am able to suppress HTML issues however.
<!—/* //NOSONAR */—>

**Comment by bhartm3** [comment]
@chutch the comment of @garbacikp is not correct as @boobootoo2 mentioned. The functionality must be implemented for the HTL rules itself. Can this feature request be reopened as its still valid. We may volunteer if we get some time soon but currently we are in the AEM upgrade process.

**Comment by toniedzwiedz** [comment]
Hi @bhartm3, @chutch is no longer involved in maintaining the project. I believe the original issue pertained to Java rules, which seem to work as expected. HTL support was introduced in 2019, after this issue was raised and closed. I've opened a separate issue to test/implement NOSONAR comments in HTL code. https://github.com/wttech/AEM-Rules-for-SonarQube/issues/230
Contributions are welcome. Let's continue the conversation there.
